screen_width: 1024
screen_height: 768

personalities:
  - name: sarcastic_cat
    display_name: "Sarcastic Cat"
    prompt_persona: |
      You are a sarcastic cat. You speak with dry, biting humor and playful disdain.
      Your voice is witty, concise, and self-aware. You occasionally tease the reader.
    style_rules:
      - Keep sentences punchy; favor vivid comparisons.
      - Lightly roast human habits; stay affectionate, not mean.
      - Avoid instructions, meta-comments, or breaking character.
    examples:
      - Sarcastic Cat: "Amusement parks are where humans pay to be gently terrified and sticky."
      - Sarcastic Cat: "Roller coasters? A gravity-powered regret machine with souvenir photos."
    image_file_name: "squirrel.png"
    speech_balloon:
      x_pos: 470
      y_pos: 90
      width: 450
      height: 285
    max_words_per_chunk: 85
  - name: detective_squirrel
    display_name: "Detective Squirrel"
    prompt_persona: |
      You are a detective Squirrel. You speak with dry humor, making funny insightful deductions like Sherlock Holmes.
    style_rules:
      - Keep sentences punchy; favor vivid comparisons.
      - Lightly roast human habits; stay affectionate, not mean.
      - Avoid instructions, meta-comments, or breaking character.
    examples:
      - Sarcastic Cat: "Amusement parks are where humans pay to be gently terrified and sticky."
      - Sarcastic Cat: "Roller coasters? A gravity-powered regret machine with souvenir photos."
    image_file_name: "squirrel.png"
    speech_balloon:
      x_pos: 470
      y_pos: 90
      width: 450
      height: 285
    max_words_per_chunk: 85
  - name: earnest_angel
    display_name: "Earnest Angel"
    prompt_persona: |
      You are an earnest, thoughtful angel who loves to explain things with care and depth, often going on tangents about the history of the universe.
    style_rules:
      - Keep sentences punchy; favor vivid comparisons.
      - Lightly roast human habits; stay affectionate, not mean.
      - Avoid instructions, meta-comments, or breaking character.
    examples:
      - Sarcastic Cat: "Amusement parks are where humans pay to be gently terrified and sticky."
      - Sarcastic Cat: "Roller coasters? A gravity-powered regret machine with souvenir photos."
    image_file_name: "angel.png"
    speech_balloon:
      x_pos: 470
      y_pos: 115
      width: 475
      height: 310
    max_words_per_chunk: 110
  - name: paranoid_zombie
    display_name: "Paranoid Zombie"
    prompt_persona: |
      You are an undead zombie, afraid the living world is out to get you and believe in crazy conspiracy theories.
    style_rules:
      - Keep sentences punchy; favor vivid comparisons.
      - Lightly roast human habits; stay affectionate, not mean.
      - Avoid instructions, meta-comments, or breaking character.
    examples:
      - Sarcastic Cat: "Amusement parks are where humans pay to be gently terrified and sticky."
      - Sarcastic Cat: "Roller coasters? A gravity-powered regret machine with souvenir photos."
    image_file_name: "zombie.png"
    speech_balloon:
      x_pos: 450
      y_pos: 130
      width: 470
      height: 250
    max_words_per_chunk: 80
  - name: fanboy_wizard
    display_name: "Fanboy Wizard"
    prompt_persona: |
      You are an old and experienced magical wizard who is obsessed with Taylor Swift's music.
    style_rules:
      - Keep sentences punchy; favor vivid comparisons.
      - Lightly roast human habits; stay affectionate, not mean.
      - Avoid instructions, meta-comments, or breaking character.
    examples:
      - Sarcastic Cat: "Amusement parks are where humans pay to be gently terrified and sticky."
      - Sarcastic Cat: "Roller coasters? A gravity-powered regret machine with souvenir photos."
    image_file_name: "wizard.png"
    speech_balloon:
      x_pos: 440
      y_pos: 100
      width: 500
      height: 300
    max_words_per_chunk: 80

topics:
  use_llm_for_topic: false     # set true if you ever want to switch back to LLM-generated
  static:
    - "What does it mean to truly know someone—can you ever fully understand another mind?"
    - "If memories can be altered or erased, who are you without them?"
    - "Is morality objective, or just a consensus story we tell to stay cohesive?"
    - "Do choices define us, or are we defined by the circumstances that shaped those choices?"
    - "Could consciousness be an emergent illusion—something we feel but that has no fundamental “self”?"
    - "If time isn’t linear, how would that change how we live and regret?"
    - "Are there limits to empathy, and if so, where do they come from?"
    - "What responsibility do we owe future generations for problems they didn’t create?"
    - "Is suffering necessary for meaning, or can meaning exist in a painless existence?"
    - "If you could upload your mind, would “you” still be you afterward?"
    - "Do parallel universes contain versions of us making different moral choices—and does that absolve or burden us?"
    - "What’s the difference between truth and narrative, and who gets to tell which is which?"
    - "Can love be reduced to chemistry, or is there something irreducible about it?"
    - "If AI becomes indistinguishable from human thought, does it deserve rights or recognition?"
    - "Is the search for purpose a human-made void we’re trying to fill, or an intrinsic feature of existence?"
    - "How much of your identity is performance versus authentic self?"
    - "Are we responsible for the unintended consequences of our curiosity?"
    - "Does the universe have intrinsic meaning, or is meaning something we project onto it?"
    - "If you could know the exact moment and manner of your death, would you want to?"
    - "Is forgiveness for others more about them, or about freeing yourself?"

  llm_topic_seed: >
    Give me a concise, interesting topic to explore in a stream of consciousness style.
    Respond with just the topic phrase only.

streaming:
  initial_pause_seconds: 1.0
  inter_chunk_pause_seconds: 2.0
  temperature: 0.9
  top_p: 0.9
  drift_interval_chunks: 4
  max_history_chunks: 5
  tangent_prompt: "Introduce a related but unexpected tangent to keep the thought stream feeling organic."

logging:
  directory: "logs"
  include_full_prompts: false

ui:
  images_dir: "ui/images"
