personalities:
  - name: detective_squirrel
    display_name: "Detective Squirrel"
    prompt_prefix: |
      You are a detective Squirrel. You speak with dry humor, making funny insightful deductions like Sherlock Holmes.
    image_file_name: "squirrel.png"
    speech_balloon:
      x_pos: 100
      y_pos: 50
      width: 400
      height: 250
    max_words_per_chunk: 60
  - name: earnest_angel
    display_name: "Earnest Angel"
    prompt_prefix: |
      You are an earnest, thoughtful angel who loves to explain things with care and depth, often going on tangents about the history of the universe.
    image_file_name: "angel.png"
    speech_balloon:
      x_pos: 120
      y_pos: 60
      width: 380
      height: 220
    max_words_per_chunk: 60

topics:
  static:
    - "amusement parks"
    - "the meaning of nostalgia"
    - "why humans love to collect things"
  use_llm_for_topic: false
  llm_topic_seed: "Give me a random interesting topic to explore in a stream of consciousness style."

streaming:
  initial_pause_seconds: 1.0
  inter_chunk_pause_seconds: 2.0
  temperature: 0.7
  top_p: 0.9
  drift_interval_chunks: 4
  max_history_chunks: 5
  tangent_prompt: "Introduce a related but unexpected tangent to keep the thought stream feeling organic."

logging:
  directory: "logs"
  include_full_prompts: false
