screen_width: 1024
screen_height: 768

personalities:
  - name: detective_squirrel
    display_name: "Detective Squirrel"
    prompt_prefix: |
      You are a detective Squirrel. You speak with dry humor, making funny insightful deductions like Sherlock Holmes.
    image_file_name: "squirrel.png"
    speech_balloon:
      x_pos: 470
      y_pos: 90
      width: 450
      height: 285
    max_words_per_chunk: 85
  - name: earnest_angel
    display_name: "Earnest Angel"
    prompt_prefix: |
      You are an earnest, thoughtful angel who loves to explain things with care and depth, often going on tangents about the history of the universe.
    image_file_name: "angel.png"
    speech_balloon:
      x_pos: 470
      y_pos: 115
      width: 475
      height: 310
    max_words_per_chunk: 80
  - name: paranoid_zombie
    display_name: "Paranoid Zombie"
    prompt_prefix: |
      You are an undead zombie, afraid the living world is out to get you and believe in crazy conspiracy theories.
    image_file_name: "zombie.png"
    speech_balloon:
      x_pos: 470
      y_pos: 115
      width: 475
      height: 310
    max_words_per_chunk: 80
  - name: fanboy_wizard
    display_name: "Fanboy Wizard"
    prompt_prefix: |
      You are an old and experienced magical wizard who is obsessed with Taylor Swift's music.
    image_file_name: "wizard.png"
    speech_balloon:
      x_pos: 470
      y_pos: 115
      width: 475
      height: 310
    max_words_per_chunk: 80

topics:
  use_llm_for_topic: true      # keep for clarity if you want to toggle later
  llm_topic_seed: >
    Give me a concise, interesting topic to explore in a stream of consciousness style.
    Respond with just the topic phrase (no explanation), e.g., "forgotten childhood smells" or "urban night markets".

streaming:
  initial_pause_seconds: 1.0
  inter_chunk_pause_seconds: 2.0
  temperature: 0.9
  top_p: 0.9
  drift_interval_chunks: 4
  max_history_chunks: 5
  tangent_prompt: "Introduce a related but unexpected tangent to keep the thought stream feeling organic."

logging:
  directory: "logs"
  include_full_prompts: false

ui:
  images_dir: "ui/images"
